import os

DATABASE_POOLSIZE        = int(os.getenv('DATABASE_POOLSIZE', "10"))
DATABASE_POOL_MINCACHED  = 1
DATABASE_POOL_MAXCACHED  = int(round(DATABASE_POOLSIZE/3))
DATABASE_NAME            = os.getenv('DATABASE_NAME', "rent_service")
DATABASE_READER_HOST     = os.getenv('DATABASE_READER_HOST')
DATABASE_WRITER_HOST     = os.getenv('DATABASE_WRITER_HOST')
DATABASE_USER            = os.getenv('DATABASE_USER')
DATABASE_PASSWORD        = os.getenv('DATABASE_PASSWORD')
DATABASE_DIALECT         = os.getenv("DATABASE_DIALECT")
DATABASE_PORT            = int(os.getenv("DATABASE_PORT", "5432"))

WRITER_HOST: str = f"{DATABASE_DIALECT}://{DATABASE_USER}:{DATABASE_PASSWORD}@{DATABASE_WRITER_HOST}:{DATABASE_PORT}/{DATABASE_NAME}" # master
READER_HOST: str = f"{DATABASE_DIALECT}://{DATABASE_USER}:{DATABASE_PASSWORD}@{DATABASE_READER_HOST}:{DATABASE_PORT}/{DATABASE_NAME}" # slave